### ISSUE TITLE
This algorithm is not working for python.

### ISSUE THREAD

**Issue by BZAghalarov** [memo735/e-olymp#8]
`def reqemcemi(x):
	cem = 0
	while x>0:
		cem = cem + x%10
		x = x//10
	return cem

def main_function(n):
	say = 0
	while n>0:
		n = n - reqemcemi(n)
		say += 1
	return say

print(main_function(int(input())))`

I make the same code for python but last 3 test cases return an error. It is not a true solution.

**Comment by memo735** [comment]
Söhbət hansı məsələnin həllindən gedir?

**Comment by BZAghalarov** [comment]
https://www.e-olymp.com/en/problems/20
Bu məsələni nezerde tutmusam.
Mumkundurse bu profile yazarsiz sizden basqa bir meselenide deqiqlesdirmek isteyirdim.
https://www.linkedin.com/in/behruzaghalarov
